# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appointment.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='appointment.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x61ppointment.proto\"O\n\x0b\x41ppointment\x12\x0f\n\x07patient\x18\x01 \x01(\x0c\x12\x10\n\x08\x64\x61tetime\x18\x02 \x01(\x0c\x12\r\n\x05notes\x18\x03 \x01(\x0c\x12\x0e\n\x06\x64octor\x18\x04 \x01(\x0c\x62\x06proto3'
)




_APPOINTMENT = _descriptor.Descriptor(
  name='Appointment',
  full_name='Appointment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='patient', full_name='Appointment.patient', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='Appointment.datetime', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notes', full_name='Appointment.notes', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='doctor', full_name='Appointment.doctor', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['Appointment'] = _APPOINTMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Appointment = _reflection.GeneratedProtocolMessageType('Appointment', (_message.Message,), {
  'DESCRIPTOR' : _APPOINTMENT,
  '__module__' : 'appointment_pb2'
  # @@protoc_insertion_point(class_scope:Appointment)
  })
_sym_db.RegisterMessage(Appointment)


# @@protoc_insertion_point(module_scope)
